# SwiftLint Configuration for FastLIFe
# Minimal working configuration to avoid SourceKit issues

# Paths to include/exclude
included:
  - FastingTracker
  - FastingTrackerTests

excluded:
  - Pods
  - fastlane
  - .build
  - docs
  - Legacy

# Rule configuration
line_length: 120
file_length:
  warning: 400
  error: 500
function_body_length:
  warning: 40
  error: 60

# Basic opt-in rules (no SourceKit dependency)
opt_in_rules:
  - empty_count
  - toggle_bool
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

# Disabled rules for now
disabled_rules:
  - missing_docs
  - todo