name: CI - Fast LIFe

on:
  push:
    branches: [ main, develop, 'feat/**' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-loc-gate:
    name: Lint & LOC Gate
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SwiftLint
      run: brew install swiftlint

    - name: Run SwiftLint
      run: |
        swiftlint lint --strict --reporter github-actions-logging

    - name: Run LOC Gate
      run: |
        bash scripts/loc_gate.sh

  build-and-test:
    name: Build & Test
    runs-on: macos-14
    needs: lint-and-loc-gate

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer

    - name: Show Xcode version
      run: xcodebuild -version

    - name: Build project
      run: |
        xcodebuild clean build \
          -project FastingTracker.xcodeproj \
          -scheme FastingTracker \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5' \
          CODE_SIGNING_ALLOWED=NO

    - name: Run unit tests
      run: |
        xcodebuild test \
          -project FastingTracker.xcodeproj \
          -scheme FastingTracker \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5' \
          CODE_SIGNING_ALLOWED=NO \
          -enableCodeCoverage YES

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          **/xcresult
